/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view; // Declares this file belongs to the "view" package

import controller.CustomerController; // Imports CustomerController controller for business logic
import exception.InvalidBookingException; // Imports custom validation exception class
import model.Customer; // Imports Customer data model (POJO)

import javax.swing.*; // Imports all Swing UI components (JPanel, JButton, JLabel, etc.)
import javax.swing.table.DefaultTableModel; // Imports DefaultTableModel Swing component
import java.sql.SQLException; // Imports SQL exception class for database error handling
import java.util.List; // Imports List interface for ordered collections
/**
 *
 * @author kabirmoulana
 */
public class CustomerPanel extends javax.swing.JPanel implements MainFrame.Refreshable { // Declares CustomerPanel — extends JPanel and implements Refreshable for auto-reload

    /**
     * Creates new form CustomerPanel
     */
    
    private final CustomerController ctrl = new CustomerController(); // Creates controller instance to handle business logic and database operations
    private DefaultTableModel tableModel; // Stores the table data model managing all rows and columns in the JTable
    private int selectedCustomerId = -1; // Tracks the database ID of the currently selected record (-1 = nothing selected)
    
    
    public CustomerPanel() { // No-arg constructor — called when this panel is first created by MainFrame
        initComponents(); // Calls NetBeans-generated method that builds and wires all UI components
        setupTable(); // Calls setupTable() to configure table columns, fonts and selection listener
        loadTable(null); // Reloads the table with fresh data from the database
    } // Closes this code block (end of method, class, or inner class)
    
    private void setupTable() { // Configures JTable appearance: columns, fonts, colours, row height, selection listener
        tableModel = new DefaultTableModel( // Creates the DefaultTableModel that holds all table rows and columns
            new String[]{"ID", "Full Name", "NIC/Passport", "Contact", "Email", "Nationality"}, 0) { // Creates an array of values representing one table row of data
            @Override public boolean isCellEditable(int r, int c) { return false; } // Returns false — table cell cannot be edited by the user
        }; // Closes this anonymous class or array definition
        tblCustomers.setModel(tableModel); // Connects the data model to this table so rows appear in the UI
        tblCustomers.setRowHeight(28); // Sets the height of each table row in pixels
        tblCustomers.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12)); // Sets the font typeface, style, and size for this component
        tblCustomers.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12)); // Sets the font typeface, style, and size for this component
        tblCustomers.getTableHeader().setBackground(new java.awt.Color(0x1A, 0x73, 0xE8)); // Sets the background fill colour of this component
        tblCustomers.getTableHeader().setForeground(java.awt.Color.WHITE); // Sets the text (foreground) colour of this component
        tblCustomers.setSelectionBackground(new java.awt.Color(0xBB, 0xDE, 0xFF)); // Sets the highlight colour shown on the selected table row
        tblCustomers.getSelectionModel().addListSelectionListener(e -> { // Registers a listener that fires when a table row is selected
            if (!e.getValueIsAdjusting() && tblCustomers.getSelectedRow() >= 0) { // Ensures a table row is actually selected before proceeding
                populateForm(); // Calls populateForm() to fill form fields from the selected table row
            } // Closes this code block (end of method, class, or inner class)
        }); // Closes the anonymous listener class and the addListener call
    } // Closes this code block (end of method, class, or inner class)

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") // Tells compiler to suppress unchecked type cast warnings
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() { // NetBeans auto-generated method — creates and configures all UI components

        titlePanel = new javax.swing.JPanel(); // Creates new JPanel component named "titlePanel"
        lblTitle = new javax.swing.JLabel(); // Creates new JLabel component named "lblTitle"
        lblSubtitle = new javax.swing.JLabel(); // Creates new JLabel component named "lblSubtitle"
        formPanel = new javax.swing.JPanel(); // Creates new JPanel component named "formPanel"
        lblId = new javax.swing.JLabel(); // Creates new JLabel component named "lblId"
        txtId = new javax.swing.JTextField(); // Creates new JTextField component named "txtId"
        lblName = new javax.swing.JLabel(); // Creates new JLabel component named "lblName"
        txtName = new javax.swing.JTextField(); // Creates new JTextField component named "txtName"
        lblNic = new javax.swing.JLabel(); // Creates new JLabel component named "lblNic"
        txtNic = new javax.swing.JTextField(); // Creates new JTextField component named "txtNic"
        lblPhone = new javax.swing.JLabel(); // Creates new JLabel component named "lblPhone"
        txtPhone = new javax.swing.JTextField(); // Creates new JTextField component named "txtPhone"
        lblEmail = new javax.swing.JLabel(); // Creates new JLabel component named "lblEmail"
        txtEmail = new javax.swing.JTextField(); // Creates new JTextField component named "txtEmail"
        lblAddress = new javax.swing.JLabel(); // Creates new JLabel component named "lblAddress"
        jScrollPane1 = new javax.swing.JScrollPane(); // Creates new JScrollPane component named "jScrollPane1"
        txtAddress = new javax.swing.JTextArea(); // Creates new JTextArea component named "txtAddress"
        lblNationality = new javax.swing.JLabel(); // Creates new JLabel component named "lblNationality"
        txtNationality = new javax.swing.JTextField(); // Creates new JTextField component named "txtNationality"
        btnPanel = new javax.swing.JPanel(); // Creates new JPanel component named "btnPanel"
        btnSave = new javax.swing.JButton(); // Creates new JButton component named "btnSave"
        btnUpdate = new javax.swing.JButton(); // Creates new JButton component named "btnUpdate"
        btnDelete = new javax.swing.JButton(); // Creates new JButton component named "btnDelete"
        btnClear = new javax.swing.JButton(); // Creates new JButton component named "btnClear"
        tablePanel = new javax.swing.JPanel(); // Creates new JPanel component named "tablePanel"
        searchPanel = new javax.swing.JPanel(); // Creates new JPanel component named "searchPanel"
        txtSearch = new javax.swing.JTextField(); // Creates new JTextField component named "txtSearch"
        btnSearch = new javax.swing.JButton(); // Creates new JButton component named "btnSearch"
        btnShowAll = new javax.swing.JButton(); // Creates new JButton component named "btnShowAll"
        jScrollPane2 = new javax.swing.JScrollPane(); // Creates new JScrollPane component named "jScrollPane2"
        tblCustomers = new javax.swing.JTable(); // Creates new JTable component named "tblCustomers"

        titlePanel.setBackground(new java.awt.Color(26, 115, 232)); // Sets the background fill colour of this component

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255)); // Sets the text (foreground) colour of this component
        lblTitle.setText("Customer Management"); // Sets visible text to: "Customer Management"

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(179, 229, 252)); // Sets the text (foreground) colour of this component
        lblSubtitle.setText("Add, update and manage customer records"); // Sets visible text to: "Add, update and manage customer records"

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel); // Creates a GroupLayout manager for precise component positioning
        titlePanel.setLayout(titlePanelLayout); // Sets the layout manager controlling how child components are positioned
        titlePanelLayout.setHorizontalGroup( // Applies horizontal layout rules to this panel
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(titlePanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addGap(20, 20, 20) // Inserts a 20px gap between components
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
                    .addComponent(lblTitle) // Places the lblTitle into this layout group
                    .addComponent(lblSubtitle)) // Places the lblSubtitle into this layout group
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) // Adds standard margins at the edge of the container
        ); // Closes the layout group or method call
        titlePanelLayout.setVerticalGroup( // Applies vertical layout rules to this panel
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(titlePanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addGap(12, 12, 12) // Inserts a 12px gap between components
                .addComponent(lblTitle) // Places the lblTitle into this layout group
                .addGap(4, 4, 4) // Inserts a 4px gap between components
                .addComponent(lblSubtitle) // Places the lblSubtitle into this layout group
                .addGap(12, 12, 12)) // Inserts a 12px gap between components
        ); // Closes the layout group or method call

        formPanel.setBackground(new java.awt.Color(255, 255, 255)); // Sets the background fill colour of this component
        formPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Details")); // Applies a visual border or padding around this component

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblId.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblId.setText("Customer ID (auto)"); // Sets visible text to: "Customer ID (auto)"

        txtId.setEditable(false); // Makes this text field read-only — user cannot type in it
        txtId.setBackground(new java.awt.Color(240, 244, 248)); // Sets the background fill colour of this component
        txtId.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtId.addActionListener(this::txtIdActionPerformed); // Registers a listener that fires when this button or field is activated

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblName.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblName.setText("Full Name *"); // Sets visible text to: "Full Name *"

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtName.addActionListener(this::txtNameActionPerformed); // Registers a listener that fires when this button or field is activated

        lblNic.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblNic.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblNic.setText("NIC / Passport *"); // Sets visible text to: "NIC / Passport *"

        txtNic.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtNic.addActionListener(this::txtNicActionPerformed); // Registers a listener that fires when this button or field is activated

        lblPhone.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblPhone.setText("Contact Number *"); // Sets visible text to: "Contact Number *"

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPhone.addActionListener(this::txtPhoneActionPerformed); // Registers a listener that fires when this button or field is activated

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblEmail.setText("Email Address"); // Sets visible text to: "Email Address"

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEmail.addActionListener(this::txtEmailActionPerformed); // Registers a listener that fires when this button or field is activated

        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblAddress.setText("Address"); // Sets visible text to: "Address"

        txtAddress.setColumns(20); // Sets the number of columns (width hint) for this text area
        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtAddress.setRows(3); // Sets the number of visible rows (height hint) for this text area
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() { // Registers a listener that fires when a key is pressed
            public void keyTyped(java.awt.event.KeyEvent evt) { // Defines the keyTyped() method
                txtAddressKeyTyped(evt); // Delegates key-typed event to the address field key handler
            } // Closes this code block (end of method, class, or inner class)
        }); // Closes the anonymous listener class and the addListener call
        jScrollPane1.setViewportView(txtAddress); // Places the component inside the scroll pane so it scrolls correctly

        lblNationality.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblNationality.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblNationality.setText("Nationality"); // Sets visible text to: "Nationality"

        txtNationality.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtNationality.addActionListener(this::txtNationalityActionPerformed); // Registers a listener that fires when this button or field is activated

        btnPanel.setOpaque(false); // Makes this component transparent so background shows through

        btnSave.setBackground(new java.awt.Color(26, 115, 232)); // Sets the background fill colour of this component
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255)); // Sets the text (foreground) colour of this component
        btnSave.setText("Save"); // Sets visible text to: "Save"
        btnSave.setOpaque(true); // Makes this component paint its own background colour
        btnSave.addActionListener(this::btnSaveActionPerformed); // Registers a listener that fires when this button or field is activated

        btnUpdate.setBackground(new java.awt.Color(0, 150, 136)); // Sets the background fill colour of this component
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255)); // Sets the text (foreground) colour of this component
        btnUpdate.setText("Update"); // Sets visible text to: "Update"
        btnUpdate.setOpaque(true); // Makes this component paint its own background colour
        btnUpdate.addActionListener(this::btnUpdateActionPerformed); // Registers a listener that fires when this button or field is activated

        btnDelete.setBackground(new java.awt.Color(198, 40, 40)); // Sets the background fill colour of this component
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255)); // Sets the text (foreground) colour of this component
        btnDelete.setText("Delete"); // Sets visible text to: "Delete"
        btnDelete.setOpaque(true); // Makes this component paint its own background colour
        btnDelete.addActionListener(this::btnDeleteActionPerformed); // Registers a listener that fires when this button or field is activated

        btnClear.setBackground(new java.awt.Color(95, 107, 124)); // Sets the background fill colour of this component
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255)); // Sets the text (foreground) colour of this component
        btnClear.setText("Clear"); // Sets visible text to: "Clear"
        btnClear.setOpaque(true); // Makes this component paint its own background colour
        btnClear.addActionListener(this::btnClearActionPerformed); // Registers a listener that fires when this button or field is activated

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel); // Creates a GroupLayout manager for precise component positioning
        btnPanel.setLayout(btnPanelLayout); // Sets the layout manager controlling how child components are positioned
        btnPanelLayout.setHorizontalGroup( // Applies horizontal layout rules to this panel
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(btnPanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addComponent(btnSave) // Places the btnSave into this layout group
                .addGap(6, 6, 6) // Inserts a 6px gap between components
                .addComponent(btnUpdate) // Places the btnUpdate into this layout group
                .addGap(6, 6, 6) // Inserts a 6px gap between components
                .addComponent(btnDelete) // Places the btnDelete into this layout group
                .addGap(6, 6, 6) // Inserts a 6px gap between components
                .addComponent(btnClear) // Places the btnClear into this layout group
                .addContainerGap(32, Short.MAX_VALUE)) // Adds standard container margin gaps at the edges of the panel
        ); // Closes the layout group or method call
        btnPanelLayout.setVerticalGroup( // Applies vertical layout rules to this panel
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) // Groups components side-by-side (parallel / same row)
            .addComponent(btnSave) // Places the btnSave into this layout group
            .addComponent(btnUpdate) // Places the btnUpdate into this layout group
            .addComponent(btnDelete) // Places the btnDelete into this layout group
            .addComponent(btnClear) // Places the btnClear into this layout group
        ); // Closes the layout group or method call

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel); // Creates a GroupLayout manager for precise component positioning
        formPanel.setLayout(formPanelLayout); // Sets the layout manager controlling how child components are positioned
        formPanelLayout.setHorizontalGroup( // Applies horizontal layout rules to this panel
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(formPanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addGap(10, 10, 10) // Inserts a 10px gap between components
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
                    .addComponent(lblId) // Places the lblId into this layout group
                    .addComponent(txtId) // Places the txtId into this layout group
                    .addComponent(lblName) // Places the lblName into this layout group
                    .addComponent(txtName) // Places the txtName into this layout group
                    .addComponent(lblNic) // Places the lblNic into this layout group
                    .addComponent(txtNic) // Places the txtNic into this layout group
                    .addComponent(lblPhone) // Places the lblPhone into this layout group
                    .addComponent(txtPhone) // Places the txtPhone into this layout group
                    .addComponent(lblEmail) // Places the lblEmail into this layout group
                    .addComponent(txtEmail) // Places the txtEmail into this layout group
                    .addComponent(lblAddress) // Places the lblAddress into this layout group
                    .addComponent(jScrollPane1) // Places the jScrollPane1 into this layout group
                    .addComponent(lblNationality) // Places the lblNationality into this layout group
                    .addComponent(txtNationality) // Places the txtNationality into this layout group
                    .addComponent(btnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) // Adds this component into the layout group at this position
                .addGap(10, 10, 10)) // Inserts a 10px gap between components
        ); // Closes the layout group or method call
        formPanelLayout.setVerticalGroup( // Applies vertical layout rules to this panel
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(formPanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblId) // Places the lblId into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblName) // Places the lblName into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblNic) // Places the lblNic into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblPhone) // Places the lblPhone into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblEmail) // Places the lblEmail into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblAddress) // Places the lblAddress into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblNationality) // Places the lblNationality into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(12, 12, 12) // Inserts a 12px gap between components
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) // Adds standard margins at the edge of the container
        ); // Closes the layout group or method call

        tablePanel.setBackground(new java.awt.Color(255, 255, 255)); // Sets the background fill colour of this component
        tablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer List")); // Applies a visual border or padding around this component

        searchPanel.setOpaque(false); // Makes this component transparent so background shows through

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSearch.addActionListener(this::txtSearchActionPerformed); // Registers a listener that fires when this button or field is activated

        btnSearch.setBackground(new java.awt.Color(26, 115, 232)); // Sets the background fill colour of this component
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255)); // Sets the text (foreground) colour of this component
        btnSearch.setText("Search"); // Sets visible text to: "Search"
        btnSearch.setOpaque(true); // Makes this component paint its own background colour
        btnSearch.addActionListener(this::btnSearchActionPerformed); // Registers a listener that fires when this button or field is activated

        btnShowAll.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnShowAll.setText("Show All"); // Sets visible text to: "Show All"
        btnShowAll.addActionListener(this::btnShowAllActionPerformed); // Registers a listener that fires when this button or field is activated

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel); // Creates a GroupLayout manager for precise component positioning
        searchPanel.setLayout(searchPanelLayout); // Sets the layout manager controlling how child components are positioned
        searchPanelLayout.setHorizontalGroup( // Applies horizontal layout rules to this panel
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(searchPanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addComponent(txtSearch) // Places the txtSearch into this layout group
                .addGap(6, 6, 6) // Inserts a 6px gap between components
                .addComponent(btnSearch) // Places the btnSearch into this layout group
                .addGap(6, 6, 6) // Inserts a 6px gap between components
                .addComponent(btnShowAll)) // Places the btnShowAll into this layout group
        ); // Closes the layout group or method call
        searchPanelLayout.setVerticalGroup( // Applies vertical layout rules to this panel
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) // Groups components side-by-side (parallel / same row)
            .addComponent(txtSearch) // Places the txtSearch into this layout group
            .addComponent(btnSearch) // Places the btnSearch into this layout group
            .addComponent(btnShowAll) // Places the btnShowAll into this layout group
        ); // Closes the layout group or method call

        tblCustomers.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblCustomers.setModel(new javax.swing.table.DefaultTableModel( // Connects the data model to this table so rows appear in the UI
            new Object [][] { // Starts the initial empty data array for the table model (no rows yet)

            }, // Closes the data array and separates it from the column names array
            new String [] { // Starts the array of column header names for the table
                "ID", "Full Name", "NIC/Passport", "Contact", "Email", "Nationality" // Column header names: ID, Full Name, NIC/Passport, Contact, Email, Nationality
            } // Closes this code block (end of method, class, or inner class)
        ) { // Opens the anonymous DefaultTableModel subclass body
            boolean[] canEdit = new boolean [] { // Boolean array defining which columns can be edited (all false = read-only)
                false, false, false, false, false, false // All columns set to false — no table cell is editable by the user
            }; // Closes this anonymous class or array definition

            public boolean isCellEditable(int rowIndex, int columnIndex) { // Overrides parent — always returns false so table cells cannot be edited
                return canEdit [columnIndex]; // Returns the value: canEdit [columnIndex]
            } // Closes this code block (end of method, class, or inner class)
        }); // Closes the anonymous listener class and the addListener call
        tblCustomers.setRowHeight(28); // Sets the height of each table row in pixels
        tblCustomers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION); // Restricts the table so only one row can be selected at a time
        tblCustomers.setShowGrid(false); // Hides grid lines between cells for a cleaner modern table look
        tblCustomers.addMouseListener(new java.awt.event.MouseAdapter() { // Registers a listener that fires on mouse click events
            public void mouseClicked(java.awt.event.MouseEvent evt) { // Defines the mouseClicked() method
                tblCustomersMouseClicked(evt); // Delegates to tblCustomersMouseClicked to handle the mouse click event
            } // Closes this code block (end of method, class, or inner class)
        }); // Closes the anonymous listener class and the addListener call
        jScrollPane2.setViewportView(tblCustomers); // Places the component inside the scroll pane so it scrolls correctly

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel); // Creates a GroupLayout manager for precise component positioning
        tablePanel.setLayout(tablePanelLayout); // Sets the layout manager controlling how child components are positioned
        tablePanelLayout.setHorizontalGroup( // Applies horizontal layout rules to this panel
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(tablePanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
                    .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Adds this component into the layout group at this position
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)) // Adds this component into the layout group at this position
                .addGap(8, 8, 8)) // Inserts a 8px gap between components
        ); // Closes the layout group or method call
        tablePanelLayout.setVerticalGroup( // Applies vertical layout rules to this panel
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(tablePanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8)) // Inserts a 8px gap between components
        ); // Closes the layout group or method call

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this); // Creates a GroupLayout manager for precise component positioning
        this.setLayout(layout); // Sets the layout manager controlling how child components are positioned
        layout.setHorizontalGroup( // Defines horizontal component arrangement for the outer frame layout
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(layout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addContainerGap() // Adds standard container margin gaps at the edges of the panel
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Adds this component into the layout group at this position
                    .addGroup(layout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                        .addGap(10, 10, 10) // Inserts a 10px gap between components
                        .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                        .addGap(10, 10, 10) // Inserts a 10px gap between components
                        .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Adds this component into the layout group at this position
                        .addGap(10, 10, 10))) // Inserts a 10px gap between components
                .addContainerGap()) // Adds standard container margin gaps at the edges of the panel
        ); // Closes the layout group or method call
        layout.setVerticalGroup( // Defines vertical component stacking for the outer frame layout
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(layout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(6, 6, 6) // Inserts a 6px gap between components
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
                    .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Adds this component into the layout group at this position
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) // Adds this component into the layout group at this position
                .addGap(10, 10, 10)) // Inserts a 10px gap between components
        ); // Closes the layout group or method call
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
        txtNic.requestFocus(); // Move focus to NIC field
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        // TODO add your handling code here:
        txtPhone.requestFocus(); // Move focus to Phone field
    }//GEN-LAST:event_txtNicActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
        txtEmail.requestFocus(); // Move focus to Email field
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressKeyTyped

    private void txtNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalityActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try { // Attempts the following database operations — errors caught below
            ctrl.addCustomer(txtName.getText(), txtNic.getText(), txtPhone.getText(), // Gets the current text content of this input field as a String
                    txtEmail.getText(), txtAddress.getText(), txtNationality.getText()); // Gets the current text content of this input field as a String
            showSuccess("Customer saved successfully."); // Shows a success dialog popup with the result message
            clearForm(); loadTable(null); // Reloads the table with fresh data from the database
        } catch (InvalidBookingException | SQLException ex) { showError(ex.getMessage()); } // Catches validation failures from the controller layer
    
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (selectedCustomerId < 0) { showError("Select a customer to update."); return; } // Checks condition and executes block if true
        try { // Attempts the following database operations — errors caught below
            ctrl.updateCustomer(selectedCustomerId, txtName.getText(), txtNic.getText(), // Gets the current text content of this input field as a String
                    txtPhone.getText(), txtEmail.getText(), txtAddress.getText(), txtNationality.getText()); // Gets the current text content of this input field as a String
            showSuccess("Customer updated successfully."); // Shows a success dialog popup with the result message
            loadTable(null); // Reloads the table with fresh data from the database
        } catch (InvalidBookingException | SQLException ex) { showError(ex.getMessage()); } // Catches validation failures from the controller layer
    
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedCustomerId < 0) { showError("Select a customer to delete."); return; } // Checks condition and executes block if true
        if (JOptionPane.showConfirmDialog(this, "Delete this customer?", "Confirm", // Checks condition and executes block if true
                JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) return; // If user clicked No or closed the dialog, exit without deleting
        try { // Attempts the following database operations — errors caught below
            ctrl.deleteCustomer(selectedCustomerId); // Passes customer ID to controller which deletes from the database
            showSuccess("Customer deleted."); clearForm(); loadTable(null); // Reloads the table with fresh data from the database
        } catch (SQLException ex) { showError("Cannot delete – customer may have linked bookings."); } // Catches database errors and shows an error message to the user
    

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearForm(); // Resets all form fields back to their empty default state
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        btnSearchActionPerformed(null); // Trigger search on Enter key
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        loadTable(txtSearch.getText().trim()); // Gets the field text and removes any leading/trailing spaces
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        // TODO add your handling code here:
        txtSearch.setText(""); loadTable(null); // Sets visible text to: ""
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void tblCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCustomersMouseClicked

    private void loadTable(String keyword) { // Fetches all records from database and populates the table rows
        try { // Attempts the following database operations — errors caught below
            List<Customer> list = (keyword == null || keyword.isEmpty()) // Returns true if the string has no characters
                    ? ctrl.getAllCustomers() : ctrl.searchCustomers(keyword); // Fetches all records from the database for this entity type
            tableModel.setRowCount(0); // Clears all existing rows from the table before reloading fresh data
            for (Customer c : list) { // Loops through each customer record from the database
                tableModel.addRow(new Object[]{ // Adds one data record as a new visible row in the table
                    c.getCustomerId(), c.getFullName(), c.getNicPassport(), // Gets the full display name of this user/customer
                    c.getContactNumber(), c.getEmail(), c.getNationality() // Adds contact number, email and nationality as the last 3 columns of this table row
                }); // Closes the anonymous listener class and the addListener call
            } // Closes this code block (end of method, class, or inner class)
        } catch (SQLException ex) { showError("Failed to load customers."); } // Catches database errors and shows an error message to the user
    } // Closes this code block (end of method, class, or inner class)

    private void populateForm() { // Reads the selected table row and fills all left-side form fields
        int row = tblCustomers.getSelectedRow(); if (row < 0) return; // Gets the index of the selected table row (-1 means no row is selected)
        selectedCustomerId = (int) tableModel.getValueAt(row, 0); // Reads the value from column 0 of the selected table row
        txtId.setText(String.valueOf(selectedCustomerId)); // Sets the display text of this component
        txtName.setText((String) tableModel.getValueAt(row, 1)); // Sets the display text of this component
        txtNic.setText((String) tableModel.getValueAt(row, 2)); // Sets the display text of this component
        txtPhone.setText((String) tableModel.getValueAt(row, 3)); // Sets the display text of this component
        txtEmail.setText(tableModel.getValueAt(row, 4) == null ? "" : (String) tableModel.getValueAt(row, 4)); // Sets the display text of this component
        try { // Attempts the following database operations — errors caught below
            model.Customer c = ctrl.getCustomerById(selectedCustomerId); // Fetches the full Customer record from the database to get address and nationality
            if (c != null) { // Checks for null to prevent NullPointerException
                txtAddress.setText(c.getAddress() == null ? "" : c.getAddress()); // Sets the display text of this component
                txtNationality.setText(c.getNationality() == null ? "" : c.getNationality()); // Sets the display text of this component
            } // Closes this code block (end of method, class, or inner class)
        } catch (SQLException ignored) {} // Catches database errors and shows an error message to the user
    } // Closes this code block (end of method, class, or inner class)

    private void clearForm() { // Resets every form field to blank and deselects any highlighted table row
        selectedCustomerId = -1; // Resets the selected customer ID to -1 (nothing selected)
        txtId.setText(""); txtName.setText(""); txtNic.setText(""); // Sets visible text to: ""
        txtPhone.setText(""); txtEmail.setText(""); // Sets visible text to: ""
        txtAddress.setText(""); txtNationality.setText(""); // Sets visible text to: ""
        tblCustomers.clearSelection(); // Removes any row highlight/selection from the table
    } // Closes this code block (end of method, class, or inner class)

    @Override // Signals this method overrides a method from the parent class or interface
    public void refresh() { loadTable(null); } // Called by MainFrame when user navigates here — reloads all data from database

    private void showSuccess(String msg) { JOptionPane.showMessageDialog(this, msg, "Success", JOptionPane.INFORMATION_MESSAGE); } // Displays a blue information dialog with a success message
    private void showError(String msg)   { JOptionPane.showMessageDialog(this, msg, "Error",   JOptionPane.ERROR_MESSAGE); } // Displays a red error dialog with the given error description


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JButton btnDelete; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JPanel btnPanel; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JButton btnSave; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JButton btnSearch; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JButton btnShowAll; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JButton btnUpdate; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JPanel formPanel; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JScrollPane jScrollPane1; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JScrollPane jScrollPane2; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblAddress; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblEmail; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblId; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblName; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblNationality; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblNic; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblPhone; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblSubtitle; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblTitle; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JPanel searchPanel; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JPanel tablePanel; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTable tblCustomers; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JPanel titlePanel; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextArea txtAddress; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtEmail; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtId; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtName; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtNationality; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtNic; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtPhone; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtSearch; // Declares a private field variable (value assigned later during initialisation)
    // End of variables declaration//GEN-END:variables
} // Closes this code block (end of method, class, or inner class)
