/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view; // Declares this file belongs to the "view" package

import dao.UserDAO;   // Used to check login credentials against the database
import model.User;    // Represents the logged-in staff member

import java.sql.SQLException; // Thrown when the database has a problem


/**
 *
 * @author kabirmoulana
 */
public class LoginForm extends javax.swing.JFrame { // Declares LoginForm as a JFrame (a standalone application window)
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName()); // Logger for writing error messages to the console output
    
    private final UserDAO userDAO = new UserDAO(); // Creates a UserDAO instance to authenticate login credentials against the database
    
    private boolean passwordVisible = false; // Tracks whether password is visible (true) or hidden as dots (false)

    /**
     * Creates new form LoginForm
     */
    public LoginForm() { // No-arg constructor — called when this panel is first created by MainFrame
        initComponents(); // Calls NetBeans-generated method that builds and wires all UI components
        setLocationRelativeTo(null);               // Centre the window on the screen
        getRootPane().setDefaultButton(btnLogin);  // Pressing Enter clicks "Sign In"
    } // Closes this code block (end of method, class, or inner class)

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") // Tells compiler to suppress unchecked type cast warnings
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAppName = new javax.swing.JLabel();
        loginCard = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblSignIn = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        passwordPanel = new javax.swing.JPanel();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox();
        lblForgotPassword = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnShowHide = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        lblAppName.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        lblAppName.setForeground(new java.awt.Color(255, 255, 255));
        lblAppName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/UI.png"))); // NOI18N

        loginCard.setBackground(new java.awt.Color(255, 255, 255));
        loginCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(13, 71, 161));
        lblWelcome.setText("Welcome Back");

        lblSignIn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSignIn.setForeground(new java.awt.Color(95, 107, 124));
        lblSignIn.setText("Please sign in to continue");

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(95, 107, 124));
        lblUsername.setText("Username");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.addActionListener(this::txtUsernameActionPerformed);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(95, 107, 124));
        lblPassword.setText("Password");

        passwordPanel.setOpaque(false);
        passwordPanel.setLayout(new java.awt.BorderLayout());

        lblRole.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRole.setForeground(new java.awt.Color(95, 107, 124));
        lblRole.setText("Role");

        cmbRole.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMIN", "RECEPTIONIST" }));
        cmbRole.addActionListener(this::cmbRoleActionPerformed);

        lblForgotPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(26, 115, 232));
        lblForgotPassword.setText("<html><u>Forgot Password?</u></html>");
        lblForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseClicked(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(198, 40, 40));
        lblError.setText(" ");

        btnLogin.setBackground(new java.awt.Color(26, 115, 232));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Sign In");
        btnLogin.setOpaque(true);
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        btnShowHide.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnShowHide.setForeground(new java.awt.Color(26, 115, 232));
        btnShowHide.setText("Show");
        btnShowHide.setContentAreaFilled(false);
        btnShowHide.setFocusPainted(false);
        btnShowHide.addActionListener(this::btnShowHideActionPerformed);

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        javax.swing.GroupLayout loginCardLayout = new javax.swing.GroupLayout(loginCard);
        loginCard.setLayout(loginCardLayout);
        loginCardLayout.setHorizontalGroup(
            loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginCardLayout.createSequentialGroup()
                        .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginCardLayout.createSequentialGroup()
                                .addComponent(lblPassword)
                                .addGap(232, 232, 232)
                                .addComponent(passwordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(loginCardLayout.createSequentialGroup()
                                .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWelcome)
                                    .addComponent(lblSignIn)
                                    .addComponent(lblUsername)
                                    .addComponent(lblForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(172, 172, 172))
                    .addGroup(loginCardLayout.createSequentialGroup()
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginCardLayout.createSequentialGroup()
                        .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginCardLayout.createSequentialGroup()
                                .addComponent(lblRole)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(181, 181, 181))
                    .addGroup(loginCardLayout.createSequentialGroup()
                        .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginCardLayout.createSequentialGroup()
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShowHide))
                            .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        loginCardLayout.setVerticalGroup(
            loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addGap(4, 4, 4)
                .addComponent(lblSignIn)
                .addGap(20, 20, 20)
                .addComponent(lblUsername)
                .addGap(26, 26, 26)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(3, 3, 3)
                .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowHide)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(lblRole)
                .addGap(18, 18, 18)
                .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblError)
                .addGap(18, 18, 18)
                .addComponent(lblForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAppName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
        txtPassword.requestFocus(); // Move keyboard focus to the password field
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
        doLogin(); // Pressing Enter in the password field triggers login
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnShowHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowHideActionPerformed
        // TODO add your handling code here:
        passwordVisible = !passwordVisible; // Flip the visible flag (true → false, false → true)

        if (passwordVisible) { // Checks current password visibility state
            // Password is now visible: show actual characters
            txtPassword.setEchoChar((char) 0); // 0 means "no masking character" = show real text
            btnShowHide.setText("Hide");        // Change button label to "Hide"
        } else { // Runs this block when none of the above conditions were true
            // Password is now hidden: show dots again
            txtPassword.setEchoChar('\u2022'); // • bullet character used as the masking dot
            btnShowHide.setText("Show");       // Change button label back to "Show"
        } // Closes this code block (end of method, class, or inner class)
    }//GEN-LAST:event_btnShowHideActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void lblForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseClicked
        // TODO add your handling code here:
        
         javax.swing.JOptionPane.showMessageDialog( // Shows a pop-up dialog box with the specified message and title
            this, // Parent window (centres the dialog on this form)
            "Please contact the phpMyAdmin administrator to reset your password.", // Message text
            "Forgot Password",                          // Dialog title
            javax.swing.JOptionPane.INFORMATION_MESSAGE // Blue (i) icon
        ); // Closes the layout group or method call
        
    }//GEN-LAST:event_lblForgotPasswordMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        doLogin(); // Delegate to the login logic method below
    }//GEN-LAST:event_btnLoginActionPerformed

    private void doLogin() { // Reads username/password/role, authenticates via UserDAO, opens MainFrame on success
        String username = txtUsername.getText().trim();                    // Get username, remove extra spaces
        String password = new String(txtPassword.getPassword()).trim();    // Get password text, remove spaces
        String role     = (String) cmbRole.getSelectedItem();             // Get chosen role (ADMIN/RECEPTIONIST)

        // Check that neither field was left empty
        if (username.isEmpty() || password.isEmpty()) { // Checks if the input field is empty — stops execution if nothing was typed
            lblError.setText("Please enter username and password."); // Show error in red
            return; // Stop here – do not try to connect to the database
        } // Closes this code block (end of method, class, or inner class)

        try { // Attempts the following database operations — errors caught below
            // Ask the UserDAO to look up these credentials in the database
            User user = userDAO.authenticate(username, password); // Declares User model variable "user"

            // Check: did we find a user AND does their role match what was selected?
            if (user != null && user.getRole().name().equals(role)) { // Checks for null to prevent NullPointerException
                // ✅ Login successful!
                dispose(); // Close the login window
                javax.swing.SwingUtilities.invokeLater(() -> { // Schedules code to run on the Swing Event Dispatch Thread (prevents UI freezes)
                    // Open the main application window on the UI thread
                    new MainFrame(user).setVisible(true); // Makes this window or component appear on screen
                }); // Closes the anonymous listener class and the addListener call
            } else { // Runs this block when none of the above conditions were true
                // ❌ Wrong username, password, or role
                lblError.setText("Invalid credentials or role mismatch."); // Show error in red
                txtPassword.setText(""); // Clear the password field for security
            } // Closes this code block (end of method, class, or inner class)
        } catch (SQLException ex) { // Catches database errors and shows an error message to the user
            // Something went wrong connecting to the database
            lblError.setText("Database error: " + ex.getMessage()); // Show the database error
        } // Closes this code block (end of method, class, or inner class)
    } // Closes this code block (end of method, class, or inner class)

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { // Defines the () method
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try { // Attempts the following database operations — errors caught below
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) { // Loops through available look-and-feel themes to find Nimbus
                if ("Nimbus".equals(info.getName())) { // Checks if the Nimbus theme is available on this system
                    javax.swing.UIManager.setLookAndFeel(info.getClassName()); // Applies the Nimbus modern look-and-feel theme to the application
                    break; // Exits the loop or switch statement immediately
                } // Closes this code block (end of method, class, or inner class)
            } // Closes this code block (end of method, class, or inner class)
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) { // Catches errors during look-and-feel setup (not fatal — falls back to default)
            logger.log(java.util.logging.Level.SEVERE, null, ex); // Logs the exception details at SEVERE level for debugging purposes
        } // Closes this code block (end of method, class, or inner class)
        //</editor-fold>
        
        // Try to apply the Nimbus look-and-feel for a modern appearance
        try { // Attempts the following database operations — errors caught below
            for (javax.swing.UIManager.LookAndFeelInfo info : // Loops through available look-and-feel themes to find Nimbus
                    javax.swing.UIManager.getInstalledLookAndFeels()) { // Gets the list of all look-and-feel themes available on this system
                if ("Nimbus".equals(info.getName())) {         // Check if Nimbus is available
                    javax.swing.UIManager.setLookAndFeel(info.getClassName()); // Apply it
                    break; // Stop searching once found
                } // Closes this code block (end of method, class, or inner class)
            } // Closes this code block (end of method, class, or inner class)
        } catch (Exception ex) { // Catches Exception and handles the error gracefully
            // Nimbus not available – Java will use its default look-and-feel instead
        } // Closes this code block (end of method, class, or inner class)


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true)); // Makes this window or component appear on screen
    } // Closes this code block (end of method, class, or inner class)

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnShowHide;
    private javax.swing.JComboBox cmbRole;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel loginCard;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
} // Closes this code block (end of method, class, or inner class)
