/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view; // Declares this file belongs to the "view" package

import controller.PackageController; // Imports PackageController controller for business logic
import exception.InvalidBookingException; // Imports custom validation exception class
import model.Package; // Imports Package data model (POJO)

import javax.swing.*; // Imports all Swing UI components (JPanel, JButton, JLabel, etc.)
import javax.swing.table.DefaultTableModel; // Imports DefaultTableModel Swing component
import java.sql.SQLException; // Imports SQL exception class for database error handling
import java.util.List; // Imports List interface for ordered collections

/**
 *
 * @author kabirmoulana
 */
public class PackagePanel extends javax.swing.JPanel implements MainFrame.Refreshable { // Declares PackagePanel — extends JPanel and implements Refreshable for auto-reload

    /**
     * Creates new form PackagePanel
     */
    
    private final PackageController ctrl = new PackageController(); // Creates controller instance to handle business logic and database operations
    private DefaultTableModel tableModel; // Stores the table data model managing all rows and columns in the JTable
    private int selectedId = -1; // Tracks the database ID of the currently selected record (-1 = nothing selected)
    
    public PackagePanel() { // No-arg constructor — called when this panel is first created by MainFrame
        initComponents(); // Calls NetBeans-generated method that builds and wires all UI components
        setupTable(); // Calls setupTable() to configure table columns, fonts and selection listener
        loadTable(null); // Reloads the table with fresh data from the database
    } // Closes this code block (end of method, class, or inner class)
    
    private void setupTable() { // Configures JTable appearance: columns, fonts, colours, row height, selection listener
        tableModel = new DefaultTableModel( // Creates the DefaultTableModel that holds all table rows and columns
            new String[]{"ID","Package Name","Destination","Days","Price (LKR)","Status"}, 0) { // Creates an array of values representing one table row of data
            @Override public boolean isCellEditable(int r, int c) { return false; } // Returns false — table cell cannot be edited by the user
        }; // Closes this anonymous class or array definition
        tblPackages.setModel(tableModel); // Connects the data model to this table so rows appear in the UI
        tblPackages.setRowHeight(28); // Sets the height of each table row in pixels
        tblPackages.setShowGrid(false); // Hides grid lines between cells for a cleaner modern table look
        tblPackages.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12)); // Sets the font typeface, style, and size for this component
        tblPackages.getTableHeader().setBackground(new java.awt.Color(0x00, 0x96, 0x88)); // Sets the background fill colour of this component
        tblPackages.getTableHeader().setForeground(java.awt.Color.WHITE); // Sets the text (foreground) colour of this component
        tblPackages.setSelectionBackground(new java.awt.Color(0xB2, 0xEB, 0xE0)); // Sets the highlight colour shown on the selected table row
        tblPackages.getSelectionModel().addListSelectionListener(e -> { // Registers a listener that fires when a table row is selected
            if (!e.getValueIsAdjusting() && tblPackages.getSelectedRow() >= 0) populateForm(); // Ensures a table row is actually selected before proceeding
        }); // Closes the anonymous listener class and the addListener call
    } // Closes this code block (end of method, class, or inner class)

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") // Tells compiler to suppress unchecked type cast warnings
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() { // NetBeans auto-generated method — creates and configures all UI components

        titlePanel = new javax.swing.JPanel(); // Creates new JPanel component named "titlePanel"
        lblTitle = new javax.swing.JLabel(); // Creates new JLabel component named "lblTitle"
        lblSubtitle = new javax.swing.JLabel(); // Creates new JLabel component named "lblSubtitle"
        formPanel = new javax.swing.JPanel(); // Creates new JPanel component named "formPanel"
        lblId = new javax.swing.JLabel(); // Creates new JLabel component named "lblId"
        txtId = new javax.swing.JTextField(); // Creates new JTextField component named "txtId"
        lblName = new javax.swing.JLabel(); // Creates new JLabel component named "lblName"
        txtName = new javax.swing.JTextField(); // Creates new JTextField component named "txtName"
        lblDest = new javax.swing.JLabel(); // Creates new JLabel component named "lblDest"
        txtDest = new javax.swing.JTextField(); // Creates new JTextField component named "txtDest"
        lblDuration = new javax.swing.JLabel(); // Creates new JLabel component named "lblDuration"
        txtDuration = new javax.swing.JTextField(); // Creates new JTextField component named "txtDuration"
        lblPrice = new javax.swing.JLabel(); // Creates new JLabel component named "lblPrice"
        txtPrice = new javax.swing.JTextField(); // Creates new JTextField component named "txtPrice"
        lblDesc = new javax.swing.JLabel(); // Creates new JLabel component named "lblDesc"
        jScrollPane1 = new javax.swing.JScrollPane(); // Creates new JScrollPane component named "jScrollPane1"
        txtDesc = new javax.swing.JTextArea(); // Creates new JTextArea component named "txtDesc"
        lblStatus = new javax.swing.JLabel(); // Creates new JLabel component named "lblStatus"
        cmbStatus = new javax.swing.JComboBox(); // Creates new JComboBox component named "cmbStatus"
        btnPanel = new javax.swing.JPanel(); // Creates new JPanel component named "btnPanel"
        btnSave = new javax.swing.JButton(); // Creates new JButton component named "btnSave"
        btnUpdate = new javax.swing.JButton(); // Creates new JButton component named "btnUpdate"
        btnDelete = new javax.swing.JButton(); // Creates new JButton component named "btnDelete"
        btnClear = new javax.swing.JButton(); // Creates new JButton component named "btnClear"
        tablePanel = new javax.swing.JPanel(); // Creates new JPanel component named "tablePanel"
        searchPanel = new javax.swing.JPanel(); // Creates new JPanel component named "searchPanel"
        txtSearch = new javax.swing.JTextField(); // Creates new JTextField component named "txtSearch"
        btnSearch = new javax.swing.JButton(); // Creates new JButton component named "btnSearch"
        btnShowAll = new javax.swing.JButton(); // Creates new JButton component named "btnShowAll"
        jScrollPane2 = new javax.swing.JScrollPane(); // Creates new JScrollPane component named "jScrollPane2"
        tblPackages = new javax.swing.JTable(); // Creates new JTable component named "tblPackages"

        titlePanel.setBackground(new java.awt.Color(0, 150, 136)); // Sets the background fill colour of this component

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255)); // Sets the text (foreground) colour of this component
        lblTitle.setText("Tour Package Management"); // Sets visible text to: "Tour Package Management"

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(178, 223, 224)); // Sets the text (foreground) colour of this component
        lblSubtitle.setText("Create and manage tour packages offered to guests"); // Sets visible text to: "Create and manage tour packages offered to guests"

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel); // Creates a GroupLayout manager for precise component positioning
        titlePanel.setLayout(titlePanelLayout); // Sets the layout manager controlling how child components are positioned
        titlePanelLayout.setHorizontalGroup( // Applies horizontal layout rules to this panel
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(titlePanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addGap(20, 20, 20) // Inserts a 20px gap between components
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
                    .addComponent(lblTitle) // Places the lblTitle into this layout group
                    .addComponent(lblSubtitle)) // Places the lblSubtitle into this layout group
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) // Adds standard margins at the edge of the container
        ); // Closes the layout group or method call
        titlePanelLayout.setVerticalGroup( // Applies vertical layout rules to this panel
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(titlePanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addGap(12, 12, 12) // Inserts a 12px gap between components
                .addComponent(lblTitle) // Places the lblTitle into this layout group
                .addGap(4, 4, 4) // Inserts a 4px gap between components
                .addComponent(lblSubtitle) // Places the lblSubtitle into this layout group
                .addGap(12, 12, 12)) // Inserts a 12px gap between components
        ); // Closes the layout group or method call

        formPanel.setBackground(new java.awt.Color(255, 255, 255)); // Sets the background fill colour of this component
        formPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Package Details")); // Applies a visual border or padding around this component

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblId.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblId.setText("Package ID (auto)"); // Sets visible text to: "Package ID (auto)"

        txtId.setEditable(false); // Makes this text field read-only — user cannot type in it
        txtId.setBackground(new java.awt.Color(240, 244, 248)); // Sets the background fill colour of this component
        txtId.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtId.addActionListener(this::txtIdActionPerformed); // Registers a listener that fires when this button or field is activated

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblName.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblName.setText("Package Name *"); // Sets visible text to: "Package Name *"

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtName.addActionListener(this::txtNameActionPerformed); // Registers a listener that fires when this button or field is activated

        lblDest.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblDest.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblDest.setText("Destination *"); // Sets visible text to: "Destination *"

        txtDest.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtDest.addActionListener(this::txtDestActionPerformed); // Registers a listener that fires when this button or field is activated

        lblDuration.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblDuration.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblDuration.setText("Duration (days) *"); // Sets visible text to: "Duration (days) *"

        txtDuration.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtDuration.addActionListener(this::txtDurationActionPerformed); // Registers a listener that fires when this button or field is activated

        lblPrice.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblPrice.setText("Price (LKR) *"); // Sets visible text to: "Price (LKR) *"

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPrice.addActionListener(this::txtPriceActionPerformed); // Registers a listener that fires when this button or field is activated

        lblDesc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblDesc.setText("Description"); // Sets visible text to: "Description"

        txtDesc.setColumns(20); // Sets the number of columns (width hint) for this text area
        txtDesc.setRows(3); // Sets the number of visible rows (height hint) for this text area
        txtDesc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtDesc.addKeyListener(new java.awt.event.KeyAdapter() { // Registers a listener that fires when a key is pressed
            public void keyTyped(java.awt.event.KeyEvent evt) { // Defines the keyTyped() method
                txtDescKeyTyped(evt); // Delegates key-typed event to the description field key handler
            } // Closes this code block (end of method, class, or inner class)
        }); // Closes the anonymous listener class and the addListener call
        jScrollPane1.setViewportView(txtDesc); // Places the component inside the scroll pane so it scrolls correctly

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(95, 107, 124)); // Sets the text (foreground) colour of this component
        lblStatus.setText("Status"); // Sets visible text to: "Status"

        cmbStatus.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVE", "INACTIVE" })); // Connects the data model to this table so rows appear in the UI
        cmbStatus.addActionListener(this::cmbStatusActionPerformed); // Registers a listener that fires when this button or field is activated

        btnPanel.setOpaque(false); // Makes this component transparent so background shows through

        btnSave.setBackground(new java.awt.Color(0, 150, 0)); // Sets the background fill colour of this component
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255)); // Sets the text (foreground) colour of this component
        btnSave.setText("Save"); // Sets visible text to: "Save"
        btnSave.setOpaque(true); // Makes this component paint its own background colour
        btnSave.addActionListener(this::btnSaveActionPerformed); // Registers a listener that fires when this button or field is activated

        btnUpdate.setBackground(new java.awt.Color(26, 115, 232)); // Sets the background fill colour of this component
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255)); // Sets the text (foreground) colour of this component
        btnUpdate.setText("Update"); // Sets visible text to: "Update"
        btnUpdate.setOpaque(true); // Makes this component paint its own background colour
        btnUpdate.addActionListener(this::btnUpdateActionPerformed); // Registers a listener that fires when this button or field is activated

        btnDelete.setBackground(new java.awt.Color(198, 40, 40)); // Sets the background fill colour of this component
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255)); // Sets the text (foreground) colour of this component
        btnDelete.setText("Delete"); // Sets visible text to: "Delete"
        btnDelete.setOpaque(true); // Makes this component paint its own background colour
        btnDelete.addActionListener(this::btnDeleteActionPerformed); // Registers a listener that fires when this button or field is activated

        btnClear.setBackground(new java.awt.Color(95, 107, 124)); // Sets the background fill colour of this component
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255)); // Sets the text (foreground) colour of this component
        btnClear.setText("Clear"); // Sets visible text to: "Clear"
        btnClear.setOpaque(true); // Makes this component paint its own background colour
        btnClear.addActionListener(this::btnClearActionPerformed); // Registers a listener that fires when this button or field is activated

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel); // Creates a GroupLayout manager for precise component positioning
        btnPanel.setLayout(btnPanelLayout); // Sets the layout manager controlling how child components are positioned
        btnPanelLayout.setHorizontalGroup( // Applies horizontal layout rules to this panel
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(btnPanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addComponent(btnSave) // Places the btnSave into this layout group
                .addGap(6, 6, 6) // Inserts a 6px gap between components
                .addComponent(btnUpdate) // Places the btnUpdate into this layout group
                .addGap(6, 6, 6) // Inserts a 6px gap between components
                .addComponent(btnDelete) // Places the btnDelete into this layout group
                .addGap(6, 6, 6) // Inserts a 6px gap between components
                .addComponent(btnClear) // Places the btnClear into this layout group
                .addContainerGap(32, Short.MAX_VALUE)) // Adds standard container margin gaps at the edges of the panel
        ); // Closes the layout group or method call
        btnPanelLayout.setVerticalGroup( // Applies vertical layout rules to this panel
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) // Groups components side-by-side (parallel / same row)
            .addComponent(btnSave) // Places the btnSave into this layout group
            .addComponent(btnUpdate) // Places the btnUpdate into this layout group
            .addComponent(btnDelete) // Places the btnDelete into this layout group
            .addComponent(btnClear) // Places the btnClear into this layout group
        ); // Closes the layout group or method call

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel); // Creates a GroupLayout manager for precise component positioning
        formPanel.setLayout(formPanelLayout); // Sets the layout manager controlling how child components are positioned
        formPanelLayout.setHorizontalGroup( // Applies horizontal layout rules to this panel
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(formPanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addGap(10, 10, 10) // Inserts a 10px gap between components
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
                    .addComponent(lblId) // Places the lblId into this layout group
                    .addComponent(txtId) // Places the txtId into this layout group
                    .addComponent(lblName) // Places the lblName into this layout group
                    .addComponent(txtName) // Places the txtName into this layout group
                    .addComponent(lblDest) // Places the lblDest into this layout group
                    .addComponent(txtDest) // Places the txtDest into this layout group
                    .addComponent(lblDuration) // Places the lblDuration into this layout group
                    .addComponent(txtDuration) // Places the txtDuration into this layout group
                    .addComponent(lblPrice) // Places the lblPrice into this layout group
                    .addComponent(txtPrice) // Places the txtPrice into this layout group
                    .addComponent(lblDesc) // Places the lblDesc into this layout group
                    .addComponent(jScrollPane1) // Places the jScrollPane1 into this layout group
                    .addComponent(lblStatus) // Places the lblStatus into this layout group
                    .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Adds this component into the layout group at this position
                    .addComponent(btnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) // Adds this component into the layout group at this position
                .addGap(10, 10, 10)) // Inserts a 10px gap between components
        ); // Closes the layout group or method call
        formPanelLayout.setVerticalGroup( // Applies vertical layout rules to this panel
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(formPanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblId) // Places the lblId into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblName) // Places the lblName into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblDest) // Places the lblDest into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(txtDest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblDuration) // Places the lblDuration into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblPrice) // Places the lblPrice into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblDesc) // Places the lblDesc into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(lblStatus) // Places the lblStatus into this layout group
                .addGap(3, 3, 3) // Inserts a 3px gap between components
                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(12, 12, 12) // Inserts a 12px gap between components
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) // Adds standard margins at the edge of the container
        ); // Closes the layout group or method call

        tablePanel.setBackground(new java.awt.Color(255, 255, 255)); // Sets the background fill colour of this component
        tablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Package List")); // Applies a visual border or padding around this component

        searchPanel.setOpaque(false); // Makes this component transparent so background shows through

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSearch.addActionListener(this::txtSearchActionPerformed); // Registers a listener that fires when this button or field is activated

        btnSearch.setBackground(new java.awt.Color(0, 150, 136)); // Sets the background fill colour of this component
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255)); // Sets the text (foreground) colour of this component
        btnSearch.setText("Search"); // Sets visible text to: "Search"
        btnSearch.setOpaque(true); // Makes this component paint its own background colour
        btnSearch.addActionListener(this::btnSearchActionPerformed); // Registers a listener that fires when this button or field is activated

        btnShowAll.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnShowAll.setText("Show All"); // Sets visible text to: "Show All"
        btnShowAll.addActionListener(this::btnShowAllActionPerformed); // Registers a listener that fires when this button or field is activated

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel); // Creates a GroupLayout manager for precise component positioning
        searchPanel.setLayout(searchPanelLayout); // Sets the layout manager controlling how child components are positioned
        searchPanelLayout.setHorizontalGroup( // Applies horizontal layout rules to this panel
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(searchPanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addComponent(txtSearch) // Places the txtSearch into this layout group
                .addGap(6, 6, 6) // Inserts a 6px gap between components
                .addComponent(btnSearch) // Places the btnSearch into this layout group
                .addGap(6, 6, 6) // Inserts a 6px gap between components
                .addComponent(btnShowAll)) // Places the btnShowAll into this layout group
        ); // Closes the layout group or method call
        searchPanelLayout.setVerticalGroup( // Applies vertical layout rules to this panel
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE) // Groups components side-by-side (parallel / same row)
            .addComponent(txtSearch) // Places the txtSearch into this layout group
            .addComponent(btnSearch) // Places the btnSearch into this layout group
            .addComponent(btnShowAll) // Places the btnShowAll into this layout group
        ); // Closes the layout group or method call

        tblPackages.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblPackages.setModel(new javax.swing.table.DefaultTableModel( // Connects the data model to this table so rows appear in the UI
            new Object [][] { // Starts the initial empty data array for the table model (no rows yet)

            }, // Closes the data array and separates it from the column names array
            new String [] { // Starts the array of column header names for the table
                "ID", "Package Name", "Destination", "Days", "Price (LKR)", "Status" // Column header names: ID, Package Name, Destination, Days, Price, Status
            } // Closes this code block (end of method, class, or inner class)
        ) { // Opens the anonymous DefaultTableModel subclass body
            boolean[] canEdit = new boolean [] { // Boolean array defining which columns can be edited (all false = read-only)
                false, false, false, false, false, false // All columns set to false — no table cell is editable by the user
            }; // Closes this anonymous class or array definition

            public boolean isCellEditable(int rowIndex, int columnIndex) { // Overrides parent — always returns false so table cells cannot be edited
                return canEdit [columnIndex]; // Returns the value: canEdit [columnIndex]
            } // Closes this code block (end of method, class, or inner class)
        }); // Closes the anonymous listener class and the addListener call
        tblPackages.setRowHeight(28); // Sets the height of each table row in pixels
        tblPackages.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION); // Restricts the table so only one row can be selected at a time
        tblPackages.setShowGrid(false); // Hides grid lines between cells for a cleaner modern table look
        tblPackages.addMouseListener(new java.awt.event.MouseAdapter() { // Registers a listener that fires on mouse click events
            public void mouseClicked(java.awt.event.MouseEvent evt) { // Defines the mouseClicked() method
                tblPackagesMouseClicked(evt); // Delegates to tblPackagesMouseClicked to handle the mouse click event
            } // Closes this code block (end of method, class, or inner class)
        }); // Closes the anonymous listener class and the addListener call
        jScrollPane2.setViewportView(tblPackages); // Places the component inside the scroll pane so it scrolls correctly

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel); // Creates a GroupLayout manager for precise component positioning
        tablePanel.setLayout(tablePanelLayout); // Sets the layout manager controlling how child components are positioned
        tablePanelLayout.setHorizontalGroup( // Applies horizontal layout rules to this panel
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(tablePanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
                    .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Adds this component into the layout group at this position
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)) // Adds this component into the layout group at this position
                .addGap(8, 8, 8)) // Inserts a 8px gap between components
        ); // Closes the layout group or method call
        tablePanelLayout.setVerticalGroup( // Applies vertical layout rules to this panel
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(tablePanelLayout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8) // Inserts a 8px gap between components
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE) // Adds this component into the layout group at this position
                .addGap(8, 8, 8)) // Inserts a 8px gap between components
        ); // Closes the layout group or method call

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this); // Creates a GroupLayout manager for precise component positioning
        this.setLayout(layout); // Sets the layout manager controlling how child components are positioned
        layout.setHorizontalGroup( // Defines horizontal component arrangement for the outer frame layout
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(layout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addContainerGap() // Adds standard container margin gaps at the edges of the panel
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Adds this component into the layout group at this position
                    .addGroup(layout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                        .addGap(10, 10, 10) // Inserts a 10px gap between components
                        .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                        .addGap(10, 10, 10) // Inserts a 10px gap between components
                        .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Adds this component into the layout group at this position
                        .addGap(10, 10, 10))) // Inserts a 10px gap between components
                .addContainerGap()) // Adds standard container margin gaps at the edges of the panel
        ); // Closes the layout group or method call
        layout.setVerticalGroup( // Defines vertical component stacking for the outer frame layout
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
            .addGroup(layout.createSequentialGroup() // Nests a sub-group inside this layout group for more complex arrangement
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE) // Adds this component into the layout group at this position
                .addGap(6, 6, 6) // Inserts a 6px gap between components
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING) // Groups components side-by-side (parallel / same row)
                    .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // Adds this component into the layout group at this position
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) // Adds this component into the layout group at this position
                .addGap(10, 10, 10)) // Inserts a 10px gap between components
        ); // Closes the layout group or method call
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
        txtDest.requestFocus(); // Move focus to Destination field
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestActionPerformed
        // TODO add your handling code here:
        txtDuration.requestFocus(); // Move focus to Duration field
    }//GEN-LAST:event_txtDestActionPerformed

    private void txtDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurationActionPerformed
        // TODO add your handling code here:
        txtPrice.requestFocus(); // Move focus to Price field
    }//GEN-LAST:event_txtDurationActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescKeyTyped

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         try { // Attempts the following database operations — errors caught below
            ctrl.addPackage(txtName.getText(), txtDest.getText(), txtDuration.getText(), txtPrice.getText(), txtDesc.getText(), Package.Status.valueOf((String)cmbStatus.getSelectedItem())); // Gets the currently selected item from the dropdown as an Object
            JOptionPane.showMessageDialog(this,"Package saved.","Success",JOptionPane.INFORMATION_MESSAGE); clearForm(); loadTable(null); // Shows a pop-up dialog box with the specified message and title
        } catch (InvalidBookingException|SQLException ex) { JOptionPane.showMessageDialog(this,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE); } // Catches validation failures from the controller layer
    
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         if (selectedId<0){JOptionPane.showMessageDialog(this,"Select a package.","Error",JOptionPane.ERROR_MESSAGE);return;} // Checks a valid record is selected before attempting an operation
        try { // Attempts the following database operations — errors caught below
            ctrl.updatePackage(selectedId, txtName.getText(), txtDest.getText(), txtDuration.getText(), txtPrice.getText(), txtDesc.getText(), Package.Status.valueOf((String)cmbStatus.getSelectedItem())); // Gets the currently selected item from the dropdown as an Object
            JOptionPane.showMessageDialog(this,"Package updated.","Success",JOptionPane.INFORMATION_MESSAGE); loadTable(null); // Shows a pop-up dialog box with the specified message and title
        } catch (InvalidBookingException|SQLException ex) { JOptionPane.showMessageDialog(this,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE); } // Catches validation failures from the controller layer
    
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedId<0){JOptionPane.showMessageDialog(this,"Select a package.","Error",JOptionPane.ERROR_MESSAGE);return;} // Checks a valid record is selected before attempting an operation
        if (JOptionPane.showConfirmDialog(this,"Delete this package?","Confirm",JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION) return; // Proceeds only if user clicked Yes in the confirmation dialog
        try { ctrl.deletePackage(selectedId); JOptionPane.showMessageDialog(this,"Deleted.","Success",JOptionPane.INFORMATION_MESSAGE); clearForm(); loadTable(null); } // Starts a try block — errors thrown here are caught in the catch block
        catch (SQLException ex) { JOptionPane.showMessageDialog(this,"Cannot delete – linked to bookings.","Error",JOptionPane.ERROR_MESSAGE); } // Shows a pop-up dialog box with the specified message and title
    
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
         clearForm(); // Resets all form fields back to their empty default state
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
         btnSearchActionPerformed(null); // Trigger search on Enter key
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        loadTable(txtSearch.getText().trim()); // Gets the field text and removes any leading/trailing spaces
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        // TODO add your handling code here:
        txtSearch.setText(""); loadTable(null); // Sets visible text to: ""
    }//GEN-LAST:event_btnShowAllActionPerformed

     private void loadTable(String keyword) { // Fetches all records from database and populates the table rows
        try { // Attempts the following database operations — errors caught below
            List<Package> list = (keyword==null||keyword.isEmpty()) ? ctrl.getAllPackages() : ctrl.searchPackages(keyword); // Returns true if the string has no characters
            tableModel.setRowCount(0); // Clears all existing rows from the table before reloading fresh data
            for (Package p : list) tableModel.addRow(new Object[]{p.getPackageId(),p.getPackageName(),p.getDestination(),p.getDurationDays(),String.format("%.2f",p.getPrice()),p.getStatus()}); // Adds one data record as a new visible row in the table
        } catch (SQLException ex) { JOptionPane.showMessageDialog(this,"Failed to load.","Error",JOptionPane.ERROR_MESSAGE); } // Catches database errors and shows an error message to the user
    } // Closes this code block (end of method, class, or inner class)
    private void populateForm() { // Reads the selected table row and fills all left-side form fields
        int row=tblPackages.getSelectedRow(); if(row<0) return; // Gets the index of the selected table row (-1 means no row is selected)
        selectedId=(int)tableModel.getValueAt(row,0); // Reads the value from column 0 of the selected table row
        txtId.setText(String.valueOf(selectedId)); txtName.setText((String)tableModel.getValueAt(row,1)); // Sets the display text of this component
        txtDest.setText((String)tableModel.getValueAt(row,2)); txtDuration.setText(String.valueOf(tableModel.getValueAt(row,3))); // Sets the display text of this component
        txtPrice.setText(String.valueOf(tableModel.getValueAt(row,4))); cmbStatus.setSelectedItem(String.valueOf(tableModel.getValueAt(row,5))); // Sets the display text of this component
        try { Package p=ctrl.getPackageById(selectedId); if(p!=null) txtDesc.setText(p.getDescription()); } catch(SQLException ignored){} // Sets the display text of this component
    } // Closes this code block (end of method, class, or inner class)
    private void clearForm() { // Resets every form field to blank and deselects any highlighted table row
        selectedId=-1; txtId.setText(""); txtName.setText(""); txtDest.setText(""); txtDuration.setText(""); txtPrice.setText(""); txtDesc.setText(""); cmbStatus.setSelectedIndex(0); tblPackages.clearSelection(); // Sets visible text to: ""
    } // Closes this code block (end of method, class, or inner class)
    @Override // Signals this method overrides a method from the parent class or interface
    public void refresh() { loadTable(null); } // Called by MainFrame when user navigates here — reloads all data from database

    private void styleLabel(javax.swing.JLabel l, String text) { l.setFont(new java.awt.Font("Segoe UI",java.awt.Font.PLAIN,11)); l.setForeground(new java.awt.Color(95,107,124)); l.setText(text); } // Sets the text (foreground) colour of this component
    private void styleBtn(javax.swing.JButton b, String text, java.awt.Color bg) { b.setFont(new java.awt.Font("Segoe UI",java.awt.Font.BOLD,12)); b.setText(text); b.setBackground(bg); b.setForeground(java.awt.Color.WHITE); b.setOpaque(true); } // Sets the background fill colour of this component

    private void tblPackagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPackagesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPackagesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JButton btnDelete; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JPanel btnPanel; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JButton btnSave; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JButton btnSearch; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JButton btnShowAll; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JButton btnUpdate; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JComboBox cmbStatus; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JPanel formPanel; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JScrollPane jScrollPane1; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JScrollPane jScrollPane2; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblDesc; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblDest; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblDuration; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblId; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblName; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblPrice; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblStatus; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblSubtitle; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JLabel lblTitle; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JPanel searchPanel; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JPanel tablePanel; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTable tblPackages; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JPanel titlePanel; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextArea txtDesc; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtDest; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtDuration; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtId; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtName; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtPrice; // Declares a private field variable (value assigned later during initialisation)
    private javax.swing.JTextField txtSearch; // Declares a private field variable (value assigned later during initialisation)
    // End of variables declaration//GEN-END:variables
} // Closes this code block (end of method, class, or inner class)
